services:
  - type: web
    name: walking-ai-demo
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py
    plan: free
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
